### ISSUE TITLE
分包问题

### ISSUE THREAD

**Issue by starryCoder** [zpsw/jt808-netty#2]
您好，非常感谢您的开源项目，对我很有帮助，在学习您项目的过程中发现您没有对分包消息做处理，我也遇到了这个问题，您有什么好的解决方案吗

**Comment by zpsw** [comment]
分包问题之所以没处理是因为缺乏一个具体场景，场景不同实现自然也不同，例如客户端是否严格按照包序发包，客户端对于子包的确认机制等等，你可以先说一下你的场景
